language: python
before_install:
  - openssl aes-256-cbc -K $encrypted_2f8017c256f6_key -iv $encrypted_2f8017c256f6_iv -in cloudflare.ini.enc -out cloudflare.ini -d
install:
  - pip install certbot certbot-dns-cloudflare
script:
  - python main.py
